// File generated by the `firebase` command line tool.
// DO NOT EDIT THIS FILE MANUALLY.

import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

TargetPlatform get defaultTargetPlatform {
  if (kIsWeb) return TargetPlatform.web;
  return defaultTargetPlatformForBrowser;
}

TargetPlatform get defaultTargetPlatformForBrowser {
  if (Platform.isWindows) return TargetPlatform.windows;
  if (Platform.isMacOS) return TargetPlatform.macOS;
  if (Platform.isLinux) return TargetPlatform.linux;
  if (Platform.isAndroid) return TargetPlatform.android;
  if (Platform.isIOS) return TargetPlatform.iOS;
  throw UnsupportedError('Unknown platform');
}

enum TargetPlatform {
  android,
  iOS,
  windows,
  linux,
  macOS,
  web,
}

/// `DefaultFirebaseOptions.currentPlatform` is supported out of the box on Web
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShNteiKsHPb_SlDs46Kc3PWtWhrBr2Rk',
    appId: '1:130112773102:web:4d52c55fe34fc005ee4cff',
    messagingSenderId: '130112773102',
    projectId: 'hrp-project-9265b',
    authDomain: 'hrp-project-9265b.firebaseapp.com',
    storageBucket: 'hrp-project-9265b.firebasestorage.app',
    measurementId: 'G-YDMV72CMY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV7llhrrEKaOS93wxLSTU2vV3Kx02Cy8I',
    appId: '1:130112773102:android:4dd3ddecbeac51e1ee4cff',
    messagingSenderId: '130112773102',
    projectId: 'hrp-project-9265b',
    storageBucket: 'hrp-project-9265b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJeJp4kC2Nyn6yzOWGt8VchEAVqXu0f1w',
    appId: '1:130112773102:ios:7849dfb14ea3bc06ee4cff',
    messagingSenderId: '130112773102',
    projectId: 'hrp-project-9265b',
    storageBucket: 'hrp-project-9265b.firebasestorage.app',
    iosClientId: '130112773102-r0rchqbakp02sfp8vdvhuacsk1s5cg5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamifiedHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJeJp4kC2Nyn6yzOWGt8VchEAVqXu0f1w',
    appId: '1:130112773102:ios:7849dfb14ea3bc06ee4cff',
    messagingSenderId: '130112773102',
    projectId: 'hrp-project-9265b',
    storageBucket: 'hrp-project-9265b.firebasestorage.app',
    iosClientId: '130112773102-r0rchqbakp02sfp8vdvhuacsk1s5cg5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.gamifiedHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShNteiKsHPb_SlDs46Kc3PWtWhrBr2Rk',
    appId: '1:130112773102:web:84d40221baaf639dee4cff',
    messagingSenderId: '130112773102',
    projectId: 'hrp-project-9265b',
    authDomain: 'hrp-project-9265b.firebaseapp.com',
    storageBucket: 'hrp-project-9265b.firebasestorage.app',
    measurementId: 'G-P2KM5871PY',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}